import type { MealTemplate } from '../types';

export const SOUP_RECIPES: MealTemplate[] = [
  {
    id: 'soup-21',
    name: 'Sopa de Funcho e Maçã Verde',
    description: 'O funcho é um dos melhores aliados para combater o inchaço e a fermentação intestinal. A maçã verde é rica em fibra e ácido málico, ajuda ao fígado e tem um efeito digestivo e alcalinizante.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'funcho', amount: 200 },
      { foodId: 'cebola', amount: 50 },
      { foodId: 'maca', amount: 100 }, // Assuming 1 small apple is about 100g
      { foodId: 'azeite', amount: 10 },
    ],
  },
  {
    id: 'soup-22',
    name: 'Creme de Curgete e Endro',
    description: 'A curgete tem um efeito diurético e hidratante, o endro estimula a digestão. As sementes de abóbora são ricas em zinco, magnésio e gorduras boas.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'curgete-abobrinha', amount: 400 },
      { foodId: 'cebola', amount: 50 },
      { foodId: 'azeite', amount: 10 },
      { foodId: 'endro', amount: 5 },
      { foodId: 'sementes-abobora', amount: 10 },
    ],
  },
  {
    id: 'soup-23',
    name: 'Creme de Couve-flor e Gengibre',
    description: 'A couve-flor é um legume rico em compostos sulfurados, essenciais para a depuração do fígado. O gengibre tem um poderoso efeito anti-inflamatório e digestivo.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'couve-flor', amount: 300 },
      { foodId: 'batata-branca-com-pele', amount: 80 },
      { foodId: 'chalota', amount: 30 },
      { foodId: 'gengibre', amount: 5 },
      { foodId: 'azeite', amount: 10 },
    ],
  },
  {
    id: 'soup-24',
    name: 'Sopa de Milho Painço com Alho-francês e Aipo',
    description: 'O milho painço é muito digestivo. O alho-francês tem propriedades prebióticas e diuréticas, enquanto o aipo estimula a diurese e ajuda a combater a retenção.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'millet', amount: 60 },
      { foodId: 'alho-frances-completo', amount: 100 },
      { foodId: 'aipo', amount: 50 },
      { foodId: 'azeite', amount: 10 },
      { foodId: 'folha-louro', amount: 1 },
    ],
  },
  {
    id: 'soup-25',
    name: 'Sopa Picante de Lentilhas Vermelhas (Estilo Indiano)',
    description: 'As lentilhas vermelhas são ricas em ferro, proteínas e fibra. As especiarias indianas facilitam a digestão, têm um efeito calorífico e reduzem a inflamação sistémica.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'lentilhas-vermelhas-cozidas', amount: 100 },
      { foodId: 'cenoura', amount: 80 },
      { foodId: 'cebola', amount: 50 },
      { foodId: 'caril-po', amount: 2 },
      { foodId: 'oleo-coco', amount: 10 },
      { foodId: 'gengibre', amount: 5 },
    ],
  },
  {
    id: 'soup-26',
    name: 'Velouté Frio de Pepino e Manjericão',
    description: 'O pepino é rico em água e minerais. O manjericão tem propriedades anti-inflamatórias e digestivas suaves, enquanto o iogurte vegetal enriquece com probióticos.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'pepino-continental', amount: 300 },
      { foodId: 'iogurte-base-coco', amount: 125 },
      { foodId: 'manjericao-fresco', amount: 6 },
      { foodId: 'sumo-de-limao', amount: 5 },
      { foodId: 'azeite', amount: 10 },
    ],
  },
  {
    id: 'soup-27',
    name: 'Sopa de Beterraba e Limão',
    description: 'A beterraba favorece a desintoxicação do fígado e a circulação. O limão melhora a digestão, reforça a imunidade e adiciona um impulso alcalinizante.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'beterraba-fresca', amount: 250 },
      { foodId: 'batata-branca-com-pele', amount: 80 },
      { foodId: 'chalota', amount: 30 },
      { foodId: 'sumo-de-limao', amount: 5 },
      { foodId: 'azeite', amount: 10 },
    ],
  },
  {
    id: 'soup-28',
    name: 'Creme de Batata Doce de Jerusalém e Nozes',
    description: 'A batata doce de Jerusalém (alcachofra) é uma excelente fonte de inulina. As nozes fornecem ómega-3, ideais para combater a inflamação e a fadiga mental.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'alcachofra-jerusalem', amount: 300 },
      { foodId: 'batata-branca-com-pele', amount: 80 },
      { foodId: 'cebola', amount: 50 },
      { foodId: 'nozes', amount: 20 },
      { foodId: 'azeite', amount: 10 },
    ],
  },
  {
    id: 'soup-29',
    name: 'Sopa de Couve-Rizada e Cenoura com Caril',
    description: 'A couve-rizada é rica em antioxidantes. As cenouras favorecem a saúde intestinal e ocular, enquanto o caril estimula a digestão e o sistema imunitário.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'couve-kale', amount: 150 },
      { foodId: 'cenoura', amount: 160 },
      { foodId: 'cebola', amount: 50 },
      { foodId: 'azeite', amount: 10 },
      { foodId: 'caril-po', amount: 2 },
    ],
  },
  {
    id: 'soup-30',
    name: 'Caldo Claro de Legumes Detox',
    description: 'Uma base simples e potente, ideal para limpeza ou em momentos de fadiga digestiva. As raízes e especiarias estimulam a drenagem.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'cenoura', amount: 80 },
      { foodId: 'aipo', amount: 130 },
      { foodId: 'cebola', amount: 50 },
      { foodId: 'gengibre', amount: 5 },
      { foodId: 'curcuma-po', amount: 2 },
      { foodId: 'folha-louro', amount: 1 },
    ],
  },
  {
    id: 'soup-47',
    name: 'Sopa Ligeira de Frango com Gengibre',
    description: 'O gengibre e o cebolinho estimulam a digestão e combatem a inflamação. O frango fornece proteínas magras, perfeitas para recuperar a energia sem pesar.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'proteina-carne-peixe', amount: 120 },
      { foodId: 'cebola', amount: 30 },
      { foodId: 'gengibre', amount: 5 },
      { foodId: 'salsa-fresca', amount: 10 },
    ],
  },
  {
    id: 'soup-56',
    name: 'Sopa de Peixe Branco e Legumes',
    description: 'O peixe branco é magro, digerível e rico em proteínas. Os legumes fornecem fibra e vitaminas, favorecendo o intestino e o metabolismo.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'proteina-carne-peixe', amount: 150 },
      { foodId: 'cenoura', amount: 80 },
      { foodId: 'curgete-abobrinha', amount: 100 },
      { foodId: 'alho-frances-completo', amount: 40 },
      { foodId: 'azeite', amount: 10 },
    ],
  },
  {
    id: 'soup-138',
    name: 'Sopa Cremosa de Cenoura e Batata',
    description: 'As cenouras são ricas em vitamina A e betacaroteno. As batatas fornecem cremosidade e saciedade, e a curcuma potencia o efeito anti-inflamatório.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'cenoura', amount: 200 },
      { foodId: 'batata-branca-com-pele', amount: 150 },
      { foodId: 'azeite', amount: 10 },
      { foodId: 'curcuma-po', amount: 2 },
    ],
  },
  {
    id: 'soup-147',
    name: 'Sopa de Cevada com Lentilhas e Legumes',
    description: 'A cevada é rica em betaglucanos e tem um efeito saciante. As lentilhas fornecem ferro e proteínas vegetais. Os legumes fornecem fibra e potássio.',
    category: 'Sopas Anti-inflamatórias',
    type: 'soup',
    items: [
      { foodId: 'cevada-cozida', amount: 60 },
      { foodId: 'lentilhas-verdes-cozidas', amount: 100 },
      { foodId: 'cenoura', amount: 80 },
      { foodId: 'aipo', amount: 50 },
      { foodId: 'cebola', amount: 50 },
      { foodId: 'azeite', amount: 10 },
    ],
  },
];
